#PBS -N transunet_train
#PBS -q testegpu
#PBS -m abe
#PBS -e transunet_train_synapse_errors 
#PBS -o transunet_train_synapse_output

export TRANSFORMERS_OFFLINE=1

module load cuda/12.0.0
source /home/lovelace/proj/proj939/rubenscp/CENAPAD/miniconda3.sh
unset CUDA_VISIBLE_DEVICES

python ~/research/white-mold-applications/TransUNet/train.py \
       --dataset Synapse \
       --vit_name R50-ViT-B_16 \
       --max_epochs 5